from time import sleep
from periphery import GPIO

HS = GPIO('/dev/gpiochip0', 13, 'out')
LS = GPIO('/dev/gpiochip4', 1, 'out')
PRE = GPIO('/dev/gpiochip4', 2, 'out')
PPT1 = GPIO('/dev/gpiochip3', 26, 'out')
PPT2 = GPIO('/dev/gpiochip3', 28, 'out')

'''
HS.write(False)
LS.write(False)
PRE.write(False)
PPT1.write(False)
PPT2.write(False)
while True:
    HS.write(True)
    LS.write(True)
    PRE.write(True)
    PPT1.write(True)
    PPT2.write(True)
    sleep(1)

    HS.write(False)
    LS.write(False)
    PRE.write(False)
    PPT1.write(False)
    PPT2.write(False)
    sleep(1)
    print("toggle")
'''

#sleep(1)
HS.write(False)
LS.write(False)
PRE.write(False)
PPT1.write(False)
PPT2.write(False)
sleep(1)
HS.write(True)
sleep(1)
LS.write(True)
sleep(1)
PRE.write(True)
sleep(1)
PPT1.write(True)
sleep(1)
PPT2.write(True)
sleep(1)
HS.write(False)
LS.write(False)
PRE.write(False)
PPT1.write(False)
PPT2.write(False)
